xmpp:
  login: "f6server@vfrc2.paata.ru"
##server: #if not same as host 
  password: "1234" #password
  keepalive: yes
  keepalive-interval: 1.5 #sec

message_pipe: 
  pipe-file: "./message.pipe" 
  to: 
    - "vfrc2@vfrc2.paata.ru" #can be list
    - "vfrc2-notebook@vfrc2.paata.ru"

cmd_exec:
  chroot: "./bin"
  filter: allow #deny
  users: 
    - "vfrc2@vfrc2.paata.ru"

