xmpp:
  login: "f6server@vfrc2.paata.ru"
##server: #if not same as host 
  password: "1234" #password
  keepalive: yes
  keepalive_interval: 1.5 #sec

message_pipe: 
  pipe-file: "./message.pipe" 
  to: "vfrc2@vfrc2@vfrc2.paata.ru" #can be list

cmd_exec:
  chroot: "./commands"
  filter: allow #deny
  users: 
    - "vfrc2@vfrc2@vfrc2.paata.ru"

